/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting.management;

import static java.awt.AWTEventMulticaster.add;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class Home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public Home() {
  
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jaddvoter = new javax.swing.JButton();
        jupdatevoter = new javax.swing.JButton();
        jdisplayvoter = new javax.swing.JButton();
        jaddcondidate = new javax.swing.JButton();
        jdiscondidatelist = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jremovevoter = new javax.swing.JButton();
        jrequest = new javax.swing.JButton();
        jdisplayfeedback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        judateteacher = new javax.swing.JButton();
        jremoveteacher = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jresult = new javax.swing.JButton();
        jcounting = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jresult1 = new javax.swing.JButton();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jsjhdsajk");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        jaddvoter.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jaddvoter.setForeground(new java.awt.Color(255, 255, 255));
        jaddvoter.setText("Add Voter");
        jaddvoter.setAutoscrolls(true);
        jaddvoter.setBorder(null);
        jaddvoter.setBorderPainted(false);
        jaddvoter.setContentAreaFilled(false);
        jaddvoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddvoterActionPerformed(evt);
            }
        });

        jupdatevoter.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jupdatevoter.setForeground(new java.awt.Color(255, 255, 255));
        jupdatevoter.setText("Update Voter");
        jupdatevoter.setBorderPainted(false);
        jupdatevoter.setContentAreaFilled(false);
        jupdatevoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdatevoterActionPerformed(evt);
            }
        });

        jdisplayvoter.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jdisplayvoter.setForeground(new java.awt.Color(255, 255, 255));
        jdisplayvoter.setText("Display Voter List");
        jdisplayvoter.setBorderPainted(false);
        jdisplayvoter.setContentAreaFilled(false);
        jdisplayvoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdisplayvoterActionPerformed(evt);
            }
        });

        jaddcondidate.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jaddcondidate.setForeground(new java.awt.Color(255, 255, 255));
        jaddcondidate.setText("Add Teacher");
        jaddcondidate.setBorder(null);
        jaddcondidate.setContentAreaFilled(false);
        jaddcondidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddcondidateActionPerformed(evt);
            }
        });

        jdiscondidatelist.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jdiscondidatelist.setForeground(new java.awt.Color(255, 255, 255));
        jdiscondidatelist.setText("Display Teacher List");
        jdiscondidatelist.setBorder(null);
        jdiscondidatelist.setContentAreaFilled(false);
        jdiscondidatelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdiscondidatelistActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Welcome ");

        jPanel3.setBackground(new java.awt.Color(0, 0, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/back.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Voter");

        jremovevoter.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jremovevoter.setForeground(new java.awt.Color(255, 255, 255));
        jremovevoter.setText("Remove Voter");
        jremovevoter.setBorder(null);
        jremovevoter.setContentAreaFilled(false);
        jremovevoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jremovevoterActionPerformed(evt);
            }
        });

        jrequest.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jrequest.setForeground(new java.awt.Color(255, 255, 255));
        jrequest.setText("Request List for Registration of Voter Page");
        jrequest.setBorderPainted(false);
        jrequest.setContentAreaFilled(false);
        jrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrequestActionPerformed(evt);
            }
        });

        jdisplayfeedback.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jdisplayfeedback.setForeground(new java.awt.Color(255, 255, 255));
        jdisplayfeedback.setText("Display Feedback Form");
        jdisplayfeedback.setBorderPainted(false);
        jdisplayfeedback.setContentAreaFilled(false);
        jdisplayfeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdisplayfeedbackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teacher");

        judateteacher.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        judateteacher.setForeground(new java.awt.Color(255, 255, 255));
        judateteacher.setText("Update Teacher");
        judateteacher.setBorder(null);
        judateteacher.setContentAreaFilled(false);
        judateteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judateteacherActionPerformed(evt);
            }
        });

        jremoveteacher.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jremoveteacher.setForeground(new java.awt.Color(255, 255, 255));
        jremoveteacher.setText("Remove Teacher");
        jremoveteacher.setBorder(null);
        jremoveteacher.setContentAreaFilled(false);
        jremoveteacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jremoveteacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jupdatevoter, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jremovevoter, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jaddcondidate, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdisplayfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(judateteacher, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jremoveteacher, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdiscondidatelist, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jdisplayvoter, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jaddvoter, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jaddvoter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jupdatevoter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jremovevoter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdisplayvoter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdisplayfeedback)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jaddcondidate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(judateteacher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jremoveteacher, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdiscondidatelist, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 610));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jresult.setText("Result of the Vote");
        jresult.setAutoscrolls(true);
        jresult.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));
        jresult.setContentAreaFilled(false);
        jresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresultActionPerformed(evt);
            }
        });

        jcounting.setText("Counting of the Vote");
        jcounting.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));
        jcounting.setContentAreaFilled(false);
        jcounting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcountingActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/voting/management/clear.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jresult1.setText("Enter Result of \"Teacher of the Year\"");
        jresult1.setAutoscrolls(true);
        jresult1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));
        jresult1.setContentAreaFilled(false);
        jresult1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresult1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcounting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jresult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jresult1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(23, 23, 23))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jcounting, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jresult, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jresult1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 250, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresultActionPerformed
votingresult v=new votingresult();
v.setVisible(true);
dispose();  
    }//GEN-LAST:event_jresultActionPerformed

    
    private void jcountingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcountingActionPerformed
       
        Counting c=new Counting();
        c.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_jcountingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        adlogin a=new adlogin();
        a.setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jdiscondidatelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdiscondidatelistActionPerformed
        displaycandidatelist d=new  displaycandidatelist();
        d.setVisible(true);
        dispose();
    }//GEN-LAST:event_jdiscondidatelistActionPerformed

    private void jaddcondidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddcondidateActionPerformed

        addTeacher a=new addTeacher();
        a.setVisible(true);
        dispose();

    }//GEN-LAST:event_jaddcondidateActionPerformed

    private void jdisplayvoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdisplayvoterActionPerformed
        Dispalyvoterlist d=new Dispalyvoterlist();
        d.setVisible(true);
        dispose();

    }//GEN-LAST:event_jdisplayvoterActionPerformed

    private void jupdatevoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jupdatevoterActionPerformed
        update up=new update();
        up.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jupdatevoterActionPerformed

    private void jaddvoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddvoterActionPerformed
        Addvoter add=new Addvoter();
        add.setVisible(true);
        dispose();

    }//GEN-LAST:event_jaddvoterActionPerformed

    private void jremovevoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jremovevoterActionPerformed
        removevoter add=new removevoter();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_jremovevoterActionPerformed

    private void jrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrequestActionPerformed
        voterrequest add=new voterrequest();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_jrequestActionPerformed

    private void jdisplayfeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdisplayfeedbackActionPerformed
   try {
        studentfeedback sf = new studentfeedback();
        sf.setVisible(true);
        dispose();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    }

    }//GEN-LAST:event_jdisplayfeedbackActionPerformed

    private void judateteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judateteacherActionPerformed
        updateT add=new updateT();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_judateteacherActionPerformed

    private void jremoveteacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jremoveteacherActionPerformed
        removeteacher add=new removeteacher();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_jremoveteacherActionPerformed

    private void jresult1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresult1ActionPerformed
        resultannouncement add=new resultannouncement();
        add.setVisible(true);
        dispose();
    }//GEN-LAST:event_jresult1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jaddcondidate;
    private javax.swing.JButton jaddvoter;
    private javax.swing.JButton jcounting;
    private javax.swing.JButton jdiscondidatelist;
    private javax.swing.JButton jdisplayfeedback;
    private javax.swing.JButton jdisplayvoter;
    private javax.swing.JButton jremoveteacher;
    private javax.swing.JButton jremovevoter;
    private javax.swing.JButton jrequest;
    private javax.swing.JButton jresult;
    private javax.swing.JButton jresult1;
    private javax.swing.JButton judateteacher;
    private javax.swing.JButton jupdatevoter;
    // End of variables declaration//GEN-END:variables
}
